package br.edu.infnet.appalbumcopa.model.domain.enums;

public enum Selecao {
    ALEMANHA,
    ARABIA_SAUDITA,
    ARGENTINA,
    AUSTRALIA,
    BELGICA,
    BRASIL,
    CAMAROES,
    CANADA,
    CATAR,
    COREIA_DO_SUL,
    COSTA_RICA,
    CROACIA,
    DINAMARCA,
    EQUADOR,
    ESPANHA,
    ESTADOS_UNIDOS,
    FRANCA,
    GANA,
    HOLANDA,
    INGLATERRA,
    IRA,
    JAPAO,
    MARROCOS,
    MEXICO,
    PAIS_DE_GALES,
    POLONIA,
    PORTUGAL,
    SENEGAL,
    SERVIA,
    SUICA,
    TUNISIA,
    URUGUAI
}
